# Generated by Django 3.2.6 on 2021-08-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanvas_app', '0002_rename_courses_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('repo', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('activity_id', models.IntegerField()),
            ],
        ),
    ]
