# Generated by Django 3.2.6 on 2021-08-06 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanvas_app', '0003_activity_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='reference_activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kanvas_app.activity'),
            preserve_default=False,
        ),
    ]
