# Generated by Django 3.2.6 on 2021-08-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanvas_app', '0004_submission_reference_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='reference_activity',
        ),
        migrations.AddField(
            model_name='submission',
            name='activities',
            field=models.ManyToManyField(related_name='submissions', to='kanvas_app.Activity'),
        ),
    ]
