# Generated by Django 3.2.6 on 2021-08-12 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanvas_app', '0008_alter_activity_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='activities',
        ),
        migrations.AlterField(
            model_name='submission',
            name='activity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanvas_app.activity'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
