# Generated by Django 3.2.6 on 2021-08-12 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanvas_app', '0009_auto_20210812_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='activity_id',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='user_id',
            new_name='user',
        ),
    ]
